import pic from '../images/pic.svg'
export const movies = [
  {
    id: 1,
    name: '33 слова о дизайне',
    image: pic,
    duration: 100,
    trailerLink: "https://www.youtube.com/watch?v=oZq_KEAcRwE",
  },
  {
    id: 2,
    name: '33 слова о дизайне',
    image: pic,
    duration: 100,
    trailerLink: "https://www.youtube.com/watch?v=oZq_KEAcRwE",
  },
  {
    id: 3,
    name: '33 слова о дизайне',
    image: pic,
    duration: 100,
    trailerLink: "https://www.youtube.com/watch?v=oZq_KEAcRwE",
  },
  {
    id: 4,
    name: '33 слова о дизайне',
    image: pic,
    duration: 100,
    trailerLink: "https://www.youtube.com/watch?v=oZq_KEAcRwE",
  },
  {
    id: 5,
    name: '33 слова о дизайне',
    image: pic,
    duration: 100,
    trailerLink: "https://www.youtube.com/watch?v=oZq_KEAcRwE",
  },
  {
    id: 6,
    name: '33 слова о дизайне',
    image: pic,
    duration: 100,
    trailerLink: "https://www.youtube.com/watch?v=oZq_KEAcRwE",
  },
  {
    id: 7,
    name: '33 слова о дизайне',
    image: pic,
    duration: 100,
    trailerLink: "https://www.youtube.com/watch?v=oZq_KEAcRwE",
  },
  {
    id: 8,
    name: '33 слова о дизайне',
    image: pic,
    duration: 100,
    trailerLink: "https://www.youtube.com/watch?v=oZq_KEAcRwE",
  },
  {
    id: 9,
    name: '33 слова о дизайне',
    image: pic,
    duration: 100,
    trailerLink: "https://www.youtube.com/watch?v=oZq_KEAcRwE",
  },
  {
    id: 10,
    name: '33 слова о дизайне',
    image: pic,
    duration: 100,
    trailerLink: "https://www.youtube.com/watch?v=oZq_KEAcRwE",
  },
  {
    id: 11,
    name: '33 слова о дизайне',
    image: pic,
    duration: 100,
    trailerLink: "https://www.youtube.com/watch?v=oZq_KEAcRwE",
  },
  {
    id: 12,
    name: '33 слова о дизайне',
    image: pic,
    duration: 100,
    trailerLink: "https://www.youtube.com/watch?v=oZq_KEAcRwE",
  },
  {
    id: 13,
    name: '33 слова о дизайне',
    image: pic,
    duration: 100,
    trailerLink: "https://www.youtube.com/watch?v=oZq_KEAcRwE",
  },
  {
    id: 14,
    name: '33 слова о дизайне',
    image: pic,
    duration: 100,
    trailerLink: "https://www.youtube.com/watch?v=oZq_KEAcRwE",
  },
  {
    id: 15,
    name: '33 слова о дизайне',
    image: pic,
    duration: 100,
    trailerLink: "https://www.youtube.com/watch?v=oZq_KEAcRwE",
  },
  {
    id: 16,
    name: '33 слова о дизайне',
    image: pic,
    duration: 100,
    trailerLink: "https://www.youtube.com/watch?v=oZq_KEAcRwE",
  },
  {
    id: 17,
    name: '33 слова о дизайне',
    image: pic,
    duration: 40,
    trailerLink: "https://www.youtube.com/watch?v=oZq_KEAcRwE",
  },
  {
    id: 18,
    name: '33 слова о дизайне',
    image: pic,
    duration: 100,
    trailerLink: "https://www.youtube.com/watch?v=oZq_KEAcRwE",
  },
  {
    id: 19,
    name: '33 слова о дизайне',
    image: pic,
    duration: 100,
    trailerLink: "https://www.youtube.com/watch?v=oZq_KEAcRwE",
  },
  {
    id: 20,
    name: '33 слова о дизайне',
    image: pic,
    duration: 100,
    trailerLink: "https://www.youtube.com/watch?v=oZq_KEAcRwE",
  }
]

export const savedMovies = [
  {
    id: 1,
    name: '33 слова о дизайне',
    image: pic,
    duration: 40,
    trailerLink: "https://www.youtube.com/watch?v=oZq_KEAcRwE",
  },
  {
    id: 2,
    name: '33 слова о дизайне',
    image: pic,
    duration: 100,
    trailerLink: "https://www.youtube.com/watch?v=oZq_KEAcRwE",
  },
  {
    id: 3,
    name: '33 слова о дизайне',
    image: pic,
    duration: 100,
    trailerLink: "https://www.youtube.com/watch?v=oZq_KEAcRwE",
  },
  {
    id: 4,
    name: '33 слова о дизайне',
    image: pic,
    duration: 100,
    trailerLink: "https://www.youtube.com/watch?v=oZq_KEAcRwE",
  },
]
