const EMAIL_VALIDATION =
  "^[A-Za-z0-9\\._%\\+\\-]+@([A-Za-z0-9\\-]+\\.)+[A-Za-z]{2,}$";

  const DESKTOP_DISPLAY = 1279;
  const TABLET_DISPLAY = 767;
  
  const MOVIE_COUNTER_WIDTH_DISPLAY_XXL = 16;
  const MOVIE_COUNTER_WIDTH_DISPLAY_XL = 8;
  const MOVIE_COUNTER_WIDTH_DISPLAY_M = 5;
  
  const MOVIE_COUNTER_FOUR = 4;
  const MOVIE_COUNTER_TWO = 2;
  
  export {
    EMAIL_VALIDATION,
    DESKTOP_DISPLAY,
    TABLET_DISPLAY,
    MOVIE_COUNTER_FOUR,
    MOVIE_COUNTER_TWO,
    MOVIE_COUNTER_WIDTH_DISPLAY_XXL,
    MOVIE_COUNTER_WIDTH_DISPLAY_XL,
    MOVIE_COUNTER_WIDTH_DISPLAY_M,
  };
